// Generated by CoffeeScript 1.4.0
var TopologyServer, assets, express, host, http, io, port;

http = require('http');

assets = require('connect-assets');

express = require('express');

io = require('socket.io');

TopologyServer = require('./topology_server');

host = 'localhost';

port = 3000;

module.exports = {
  start: function(root) {
    var app, server, socket;
    app = express();
    app.set('views', root + '/views');
    app.set('view engine', 'jade');
    app.use(express.logger('dev'));
    app.use(assets());
    app.use(express["static"](root + '/public'));
    app.get('/', function(req, res) {
      return res.render('index');
    });
    app.get('/client.html', function(req, res) {
      return res.render('client');
    });
    server = http.createServer(app);
    socket = io.listen(server);
    new TopologyServer({
      app: app,
      socket: socket
    });
    return server.listen(port, host, function() {
      return console.log('http://%s:%s', server.address().address, server.address().port);
    });
  }
};
