// Generated by CoffeeScript 1.4.0
var assets, express, http;

http = require('http');

assets = require('connect-assets');

express = require('express');

module.exports = {
  start: function(root) {
    var app;
    app = express();
    app.set('views', root + '/views');
    app.set('view engine', 'jade');
    app.use(express.logger('dev'));
    app.use(assets());
    app.use(express["static"](root + '/public'));
    app.get('/', function(req, res) {
      return res.render('index');
    });
    app.get('/client.html', function(req, res) {
      return res.render('client');
    });
    return http.createServer(app).listen(3000, function() {
      return console.log('http://localhost:3000');
    });
  }
};
