// Generated by CoffeeScript 1.4.0
var ShapeCache, ShapeFile;

ShapeFile = require('node-shapelib-partial').ShapeFile;

ShapeCache = (function() {

  function ShapeCache(properties) {
    var prop;
    for (prop in properties) {
      this[prop] = properties[prop];
    }
    if (!this.path) {
      throw 'missing path';
    }
    this.shapeFiles = {};
    this.shapes = {};
  }

  ShapeCache.prototype.loadShapes = function(id, callback) {
    var file,
      _this = this;
    if (this.shapes[id]) {
      console.log('cached shapes "%s"', id);
      callback(null, this.shapes[id]);
      return;
    }
    console.log('load shapes "%s" from file', id);
    file = this.path + '/' + id;
    this.shapeFiles[id] = new ShapeFile;
    return this.shapeFiles[id].open(file, function(error, shapes) {
      if (error) {
        callback(error);
        return;
      }
      _this.shapes[id] = shapes;
      return callback(null, shapes);
    });
  };

  return ShapeCache;

})();

module.exports = ShapeCache;
