// Generated by CoffeeScript 1.4.0
var ShapeServer;

ShapeServer = (function() {

  function ShapeServer(properties) {
    var prop,
      _this = this;
    for (prop in properties) {
      this[prop] = properties[prop];
    }
    if (!this.app) {
      throw 'missing app';
    }
    if (!this.sockets) {
      throw 'missing sockets';
    }
    if (!this.cache) {
      throw 'missing cache';
    }
    this.sockets.on('connection', function(socket) {
      return socket.on('shape:register', function(payload) {
        var id;
        id = payload.id;
        return _this.loadShapes(id, function(err, shapes) {
          return socket.emit('shape:register:ack', shapes);
        });
      });
    });
  }

  ShapeServer.prototype.loadShapes = function(id, callback) {
    console.log('TODO: multiple concurrent clients on requesting the same uncached tile cause a simultanoues load from disk');
    return this.cache.loadShapes(id, callback);
  };

  return ShapeServer;

})();

module.exports = ShapeServer;
