// Generated by CoffeeScript 1.4.0
var GeoTiff, TileCache;

GeoTiff = require('./geo_tiff');

TileCache = (function() {

  function TileCache(properties) {
    var prop;
    for (prop in properties) {
      this[prop] = properties[prop];
    }
    if (!this.type) {
      throw 'missing type';
    }
    if (this.type === 'GeoTiff' && !this.path) {
      throw 'missing path';
    }
    if (!this.prefix) {
      this.prefix = '';
    }
    if (!this.suffix) {
      this.suffix = '';
    }
    this.tiles = {};
  }

  TileCache.prototype.loadTile = function(id, callback) {
    var file,
      _this = this;
    if (this.tiles[id]) {
      console.log('cached tile "%s"', id);
      callback(null, this.tiles[id]);
      return;
    }
    console.log('load tile "%s" from file', id);
    file = this.path + '/' + this.prefix + id + this.suffix;
    return new GeoTiff(file).loadFile(function(err, tile) {
      if (err) {
        callback(err);
        return;
      }
      _this.tiles[id] = tile;
      return callback(null, tile);
    });
  };

  return TileCache;

})();

module.exports = TileCache;
