// Generated by CoffeeScript 1.4.0
var TopologyServer;

TopologyServer = (function() {

  function TopologyServer(properties) {
    var prop;
    for (prop in properties) {
      this[prop] = properties[prop];
    }
    if (!this.app) {
      throw 'missing app';
    }
    if (!this.socket) {
      throw 'missing socket';
    }
  }

  return TopologyServer;

})();

module.exports = TopologyServer;
